// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: proto/pingometr.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFastestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetFastestRequest) Reset() {
	*x = GetFastestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pingometr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFastestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFastestRequest) ProtoMessage() {}

func (x *GetFastestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pingometr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFastestRequest.ProtoReflect.Descriptor instead.
func (*GetFastestRequest) Descriptor() ([]byte, []int) {
	return file_proto_pingometr_proto_rawDescGZIP(), []int{0}
}

type GetSlowestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetSlowestRequest) Reset() {
	*x = GetSlowestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pingometr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSlowestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSlowestRequest) ProtoMessage() {}

func (x *GetSlowestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pingometr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSlowestRequest.ProtoReflect.Descriptor instead.
func (*GetSlowestRequest) Descriptor() ([]byte, []int) {
	return file_proto_pingometr_proto_rawDescGZIP(), []int{1}
}

type GetSpecificRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SiteName string `protobuf:"bytes,1,opt,name=siteName,proto3" json:"siteName,omitempty"`
}

func (x *GetSpecificRequest) Reset() {
	*x = GetSpecificRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pingometr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSpecificRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpecificRequest) ProtoMessage() {}

func (x *GetSpecificRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pingometr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpecificRequest.ProtoReflect.Descriptor instead.
func (*GetSpecificRequest) Descriptor() ([]byte, []int) {
	return file_proto_pingometr_proto_rawDescGZIP(), []int{2}
}

func (x *GetSpecificRequest) GetSiteName() string {
	if x != nil {
		return x.SiteName
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *PingUser `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pingometr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pingometr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_pingometr_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetResponse() *PingUser {
	if x != nil {
		return x.Response
	}
	return nil
}

type PingUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ping  int32  `protobuf:"varint,1,opt,name=ping,proto3" json:"ping,omitempty"`
	Site  string `protobuf:"bytes,2,opt,name=site,proto3" json:"site,omitempty"`
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *PingUser) Reset() {
	*x = PingUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pingometr_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingUser) ProtoMessage() {}

func (x *PingUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pingometr_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingUser.ProtoReflect.Descriptor instead.
func (*PingUser) Descriptor() ([]byte, []int) {
	return file_proto_pingometr_proto_rawDescGZIP(), []int{4}
}

func (x *PingUser) GetPing() int32 {
	if x != nil {
		return x.Ping
	}
	return 0
}

func (x *PingUser) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *PingUser) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetAdminDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAdminDataRequest) Reset() {
	*x = GetAdminDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pingometr_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAdminDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminDataRequest) ProtoMessage() {}

func (x *GetAdminDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pingometr_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminDataRequest.ProtoReflect.Descriptor instead.
func (*GetAdminDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_pingometr_proto_rawDescGZIP(), []int{5}
}

type GetAdminDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*PingAdmin `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetAdminDataResponse) Reset() {
	*x = GetAdminDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pingometr_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAdminDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminDataResponse) ProtoMessage() {}

func (x *GetAdminDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pingometr_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminDataResponse.ProtoReflect.Descriptor instead.
func (*GetAdminDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_pingometr_proto_rawDescGZIP(), []int{6}
}

func (x *GetAdminDataResponse) GetData() []*PingAdmin {
	if x != nil {
		return x.Data
	}
	return nil
}

type PingAdmin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ping    int32  `protobuf:"varint,1,opt,name=ping,proto3" json:"ping,omitempty"`
	Site    string `protobuf:"bytes,2,opt,name=site,proto3" json:"site,omitempty"`
	Error   string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	NErrors int32  `protobuf:"varint,4,opt,name=nErrors,proto3" json:"nErrors,omitempty"`
	NMax    int32  `protobuf:"varint,5,opt,name=nMax,proto3" json:"nMax,omitempty"`
	NMin    int32  `protobuf:"varint,6,opt,name=nMin,proto3" json:"nMin,omitempty"`
}

func (x *PingAdmin) Reset() {
	*x = PingAdmin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pingometr_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingAdmin) ProtoMessage() {}

func (x *PingAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pingometr_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingAdmin.ProtoReflect.Descriptor instead.
func (*PingAdmin) Descriptor() ([]byte, []int) {
	return file_proto_pingometr_proto_rawDescGZIP(), []int{7}
}

func (x *PingAdmin) GetPing() int32 {
	if x != nil {
		return x.Ping
	}
	return 0
}

func (x *PingAdmin) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *PingAdmin) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PingAdmin) GetNErrors() int32 {
	if x != nil {
		return x.NErrors
	}
	return 0
}

func (x *PingAdmin) GetNMax() int32 {
	if x != nil {
		return x.NMax
	}
	return 0
}

func (x *PingAdmin) GetNMin() int32 {
	if x != nil {
		return x.NMin
	}
	return 0
}

var File_proto_pingometr_proto protoreflect.FileDescriptor

var file_proto_pingometr_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x69, 0x6e, 0x67, 0x6f, 0x6d, 0x65, 0x74,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x22, 0x13, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x46, 0x61, 0x73, 0x74, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x6c, 0x6f, 0x77, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x30, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63,
	0x69, 0x66, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73,
	0x69, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x69, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x37, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69,
	0x6e, 0x67, 0x55, 0x73, 0x65, 0x72, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x48, 0x0a, 0x08, 0x50, 0x69, 0x6e, 0x67, 0x55, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x73, 0x69, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x15, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x39, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69, 0x6e,
	0x67, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x8b, 0x01, 0x0a,
	0x09, 0x50, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x69,
	0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x69, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69,
	0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x4d, 0x61, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x6e, 0x4d, 0x61, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x4d, 0x69, 0x6e, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6e, 0x4d, 0x69, 0x6e, 0x32, 0xf2, 0x01, 0x0a, 0x09, 0x50,
	0x69, 0x6e, 0x67, 0x4f, 0x6d, 0x65, 0x74, 0x72, 0x12, 0x34, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x46,
	0x61, 0x73, 0x74, 0x65, 0x73, 0x74, 0x12, 0x15, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x46,
	0x61, 0x73, 0x74, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34,
	0x0a, 0x0a, 0x47, 0x65, 0x74, 0x53, 0x6c, 0x6f, 0x77, 0x65, 0x73, 0x74, 0x12, 0x15, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x6c, 0x6f, 0x77, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x69,
	0x66, 0x69, 0x63, 0x12, 0x16, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63,
	0x69, 0x66, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x17, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_pingometr_proto_rawDescOnce sync.Once
	file_proto_pingometr_proto_rawDescData = file_proto_pingometr_proto_rawDesc
)

func file_proto_pingometr_proto_rawDescGZIP() []byte {
	file_proto_pingometr_proto_rawDescOnce.Do(func() {
		file_proto_pingometr_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_pingometr_proto_rawDescData)
	})
	return file_proto_pingometr_proto_rawDescData
}

var file_proto_pingometr_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_pingometr_proto_goTypes = []interface{}{
	(*GetFastestRequest)(nil),    // 0: v1.GetFastestRequest
	(*GetSlowestRequest)(nil),    // 1: v1.GetSlowestRequest
	(*GetSpecificRequest)(nil),   // 2: v1.GetSpecificRequest
	(*GetResponse)(nil),          // 3: v1.GetResponse
	(*PingUser)(nil),             // 4: v1.PingUser
	(*GetAdminDataRequest)(nil),  // 5: v1.GetAdminDataRequest
	(*GetAdminDataResponse)(nil), // 6: v1.GetAdminDataResponse
	(*PingAdmin)(nil),            // 7: v1.PingAdmin
}
var file_proto_pingometr_proto_depIdxs = []int32{
	4, // 0: v1.GetResponse.response:type_name -> v1.PingUser
	7, // 1: v1.GetAdminDataResponse.data:type_name -> v1.PingAdmin
	0, // 2: v1.PingOmetr.GetFastest:input_type -> v1.GetFastestRequest
	1, // 3: v1.PingOmetr.GetSlowest:input_type -> v1.GetSlowestRequest
	2, // 4: v1.PingOmetr.GetSpecific:input_type -> v1.GetSpecificRequest
	5, // 5: v1.PingOmetr.GetAdminData:input_type -> v1.GetAdminDataRequest
	3, // 6: v1.PingOmetr.GetFastest:output_type -> v1.GetResponse
	3, // 7: v1.PingOmetr.GetSlowest:output_type -> v1.GetResponse
	3, // 8: v1.PingOmetr.GetSpecific:output_type -> v1.GetResponse
	6, // 9: v1.PingOmetr.GetAdminData:output_type -> v1.GetAdminDataResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_pingometr_proto_init() }
func file_proto_pingometr_proto_init() {
	if File_proto_pingometr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_pingometr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFastestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pingometr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSlowestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pingometr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSpecificRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pingometr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pingometr_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pingometr_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAdminDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pingometr_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAdminDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pingometr_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingAdmin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_pingometr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pingometr_proto_goTypes,
		DependencyIndexes: file_proto_pingometr_proto_depIdxs,
		MessageInfos:      file_proto_pingometr_proto_msgTypes,
	}.Build()
	File_proto_pingometr_proto = out.File
	file_proto_pingometr_proto_rawDesc = nil
	file_proto_pingometr_proto_goTypes = nil
	file_proto_pingometr_proto_depIdxs = nil
}
